# Generated by Django 3.1.7 on 2021-03-26 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.AutoField(default=main.models.Memes.get_uuid_no_dash, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, upload_to=main.models.get_memes_picture_upload_path)),
                ('video', models.FileField(blank=True, upload_to=main.models.get_memes_video_upload_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MemesFavourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('memes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.memes')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='memes',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', through='main.MemesFavourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memes',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memes',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('meme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.memes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
